import * as dotenv from 'dotenv';

dotenv.config();

const {
  MONGO_USER,
  MONGO_PASSWORD,
  MONGO_HOST,
  MONGO_PORT,
  MONGO_DB_NAME,
  TEST_MONGO_USER,
  TEST_MONGO_PASSWORD,
  TEST_MONGO_HOST,
  TEST_MONGO_PORT,
  TEST_MONGO_DB_NAME,
  NODE_INTERNAL_PORT, // Port inside Docker container
  AWS_ACCESS_KEY_ID,
  AWS_ACCESS_KEY_SECRET,
  AWS_BUCKET_NAME,
  CLOUDFRONT_DISTRIBUTION_URL,
} = process.env;

const TEST_MONGO_URI = `mongodb://${TEST_MONGO_USER}:${TEST_MONGO_PASSWORD}@${TEST_MONGO_HOST}:${TEST_MONGO_PORT}/${TEST_MONGO_DB_NAME}?retryWrites=true&w=majority`;
const PROD_MONGO_URI = `mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?retryWrites=true&w=majority`;

const MONGO_URI =
  process.env.NODE_ENV === 'test' ? TEST_MONGO_URI : PROD_MONGO_URI;

export default {
  MONGO_URI,
  NODE_INTERNAL_PORT,
  AWS_ACCESS_KEY_ID,
  AWS_ACCESS_KEY_SECRET,
  AWS_BUCKET_NAME,
  CLOUDFRONT_DISTRIBUTION_URL,
};
